PORT: 2023
PREFIX: api

# token过期时间为7天
tokenExpire: 7

# 数据库配置
datasource:
  driverName: mysql
  host: localhost
  port: 3306
  database: nestjs-rbac
  username: root
  password: 123456
  charset: utf8mb4
  loc: Asia/Shanghai
  logging: true

# 初始化数据
user:
  username: admin
  password: 123456
  nickname: 系统管理员

# jwt 配置
jwt:
  secretkey: 'zANDwNQVFzxlfG9myPxVWAkq4iXJEPhI'
  expiresin: '1h'
  refreshExpiresIn: '2h'
